.gitignore, package-lock.json, package.json
- npm init
- gitignore
- 기본 모듈 설치
- webpack, babel 제외
=> [#1] wip: 공통 개발 환경 구성 - 1

.babelrc, .eslintrc.json, .prettierrc, package-lock.json, package.json, tsconfig.json, webpack.config.js
=> [#1] wip: 공통 개발 환경 구성 - 2

.gitignore, package-lock.json, package.json, src/main.js, src/models/index.js, tsconfig.json
=> 백엔드 개발 환경 구성 완료

tsconfig.json, webpack.config.js
resolve #26 
- tsconfig.json
- 주석처리
- webpack.config.js
- devtool : inline-source-map 추가
=> [#26] refactor: tsconfig 수정

client/src/app.ts, client/src/components/Account.ts, client/src/components/Category.ts, client/src/components/Chatting.ts, client/src/components/ChattingDetail.ts, client/src/components/Login.ts, client/src/components/Main.ts, client/src/components/Menu.ts, client/src/components/Post.ts, client/src/components/Region.ts, client/src/components/Signin.ts, client/src/components/Write.ts, client/src/index.html, client/src/styles/App.scss
일단 완성했습니다~~~
커밋에 설명 잘 써놨어요
궁금한거있으면 물어보세요
=> [#9] wip: 최상위 모듈 기본틀 완성

server/src/main.js, server/src/passport/index.js, server/src/routes/auth.js
=> [#6, #12] wip: 로그인 관련 내용입니다.

client/src/layout-example.html, client/src/styles/index.scss, client/src/styles/mixins.scss, client/webpack.config.js
작업 내용은 커밋 메세지와 같으며, 주요 변경사항은 아래와 같습니다.  
- file-loader 경로 수정
- 스타일 관련 네이밍 변경 및 작업
공통 UI 목록
=> [#6] wip: 공통 UI 작업 및 예시 파일 추가입니다.

client/src/app.ts, client/src/components/Main.ts, client/src/styles/App.scss, client/webpack.config.js
일단 대략적으로 코드는 돌아가게 해놨고 추후 계속 수정해서 올리겠습니다.
=> [#9] 메인화면 프론트엔드 대략적인 완성?

client/src/app.ts, client/src/components/Main.ts, client/src/styles/Main.scss, client/src/styles/index.scss
- 일단은 생각나는것들 전부다 구현해놨습니다.
- 테스트는 제가 했는데 일단 에러는 없습니다.(발견될지도??)
- resolve는 일단 안하는걸로...
=> #9 메인화면 및 메인모듈 완성?

client/src/components/Category.ts, client/src/styles/index.scss
- 더미데이터, tmpList를 통해 동작하고 있습니다!  
- 선택시 효과 및 상태변경에 대한 처리가 필요하여 작업 중이라는 제목으로 설정했습니다!
=> [#13] wip: 카테고리 UI 구현 작업 중

client/src/components/Menu.ts, client/src/styles/index.scss, client/src/styles/menu.scss, client/src/styles/mixins.scss
- 팝업 토글을 제외하고 처리된 상태입니다!
- 찜하기 아이콘은 슬랙에 올라온 폰트를 쓰려다가 기존 계획대로 이미지를 교체하기로 했습니다!
=> [#15] wip: 메뉴 UI 작업 중

client/src/components/Login.ts, client/src/components/Main.ts, client/src/styles/Login.scss, client/src/styles/Main.scss
실수로 커밋을 로그인까지 했네요..
급해서 그랬나봅니다
=> [#9] 메인화면 자잘한거 추가, 로그인 기능 구현

server/src/passport/index.js, server/src/routes/auth.js
일단 로그인은 돌아가게 구현해놨습니다.
주말에 코드수정을 해야되서 resolve는 하지 않겠습니다.
=> #12 Be/auth 완성?

client/src/app.ts, client/src/components/Account.ts
=> [#11] bug:  내계정에서 뒤로가기 추가

client/src/app.ts, client/src/components/Account.ts, client/src/components/Category.ts, client/src/components/Chatting.ts, client/src/components/ChattingDetail.ts, client/src/components/Login.ts, client/src/components/Main.ts, client/src/components/Menu.ts, client/src/components/Post.ts, client/src/components/Region.ts, client/src/components/Signup.ts, client/src/components/Write.ts, server/src/routes/auth.js
=> 금요일 배포버전 리팩토링

client/src/app.ts, client/src/components/Region.ts, client/src/styles/Region.scss, client/src/styles/index.scss
일단 서버는 만들지 않았는데 조만간?? 오늘?? 서버 테스트하고 서버도 올리겠습니다
커밋에 상세내용은 적어놨어요
=> #30 내동네 프론트엔드 구현

client/src/app.ts, client/src/components/Account.ts, client/src/components/Category.ts, client/src/components/Login.ts, client/src/components/Main.ts, client/src/components/Menu.ts, client/src/components/Region.ts, client/src/components/Signup.ts, client/src/styles/App.scss, client/src/styles/Region.scss
resolve #54 
- 말씀하신 애니메이션 margin을 transition으로 변경
- 코드 리팩토링
=> 애니메이션 transition, 리팩토링

client/src/app.ts, client/src/components/Account.ts, client/src/components/Category.ts, client/src/components/Login.ts, client/src/components/Main.ts, client/src/components/Menu.ts, client/src/components/Region.ts, client/src/components/Signup.ts, client/src/styles/App.scss, client/src/styles/Region.scss, server/src/routes/region.js
resolve #32 
- 특별한 것 없습니다. 그냥 create, delete만 넣었어요
- 미들웨어도 적용
=> Be/region create, delete 구현

client/src/app.ts, client/src/components/Account.ts, client/src/components/Category.ts, client/src/components/Login.ts, client/src/components/Main.ts, client/src/components/Menu.ts, client/src/components/Region.ts, client/src/components/Signup.ts, client/src/styles/App.scss, client/src/styles/Region.scss, server/src/routes/region.js
resolve #31 
- 내지역 프로트 구현했습니다.
- 커밋메세지에 적어놨어요 상세내용은
=> Fe/region 

server/src/main.js, server/src/passport/index.js
=> [#5] wip: 패스포트 deserialize db 접근 줄이기

client/package-lock.json, client/package.json, client/webpack.common.js, client/webpack.dev.js, client/webpack.prod.js, server/src/main.js, server/src/passport/index.js
=> Fe/webpack 배포 설정 추가

client/package-lock.json, client/package.json, client/src/app.ts, client/src/components/Main.ts, client/src/components/Write.ts, client/src/styles/Main.scss, client/src/styles/Write.scss, client/src/styles/index.scss, client/webpack.common.js, client/webpack.dev.js, client/webpack.prod.js, server/src/main.js, server/src/passport/index.js, server/src/routes/category.js
커밋 메시지에 내용 적어놨습니다.
오늘 글쓰기 끝내버리죠
=> Fe/write 글쓰기 프론트 구현

client/src/components/Region.ts
- 삭제되었을 때 active 클래스가 적용되지 않는 문제 발견.
- 해결
=> [#30] bug: :bug: 내 동네 오류 수정

client/src/app.ts, client/src/components/Login.ts, client/src/components/Main.ts, client/src/components/Region.ts, client/src/components/Write.ts, client/src/styles/menu.scss
=> [#30] Fe/main 오류 및 리팩토링

server/src/routes/goods-photo.js
사진 업로드 후 리턴 형식입니다
```json
{
data : [
'http...',
'http...',
...
]
}
```
=> [#18] wip: :gear: 사진 업로드 후 url 리턴처리

server/src/controllers/goods.controller.js, server/src/queries/goods.query.js, server/src/services/goods.service.js
- req.uest.id
- req.user.id
- req.user_id
- req.body.userId
- 목록에서도 지역명 반환
=> [#18] bug: 테스트 중 발견한 버그 수정

server/src/queries/goods.query.js
region join이 누락한 부분 추가 했습니다 :)
=> [#18] bug: join region 추가

server/src/queries/goods.query.js, server/src/routes/region.js
- 상품 리스트 삭제 상품 비노출
- 지역 추가 uuid id 변경 누락분 수정
=> [#18] bug: 상품 리스트, 지역

client/src/app.ts, client/src/components/Category.ts, client/src/components/Main.ts, client/src/styles/Category.scss, server/src/queries/goods.query.js, server/src/routes/category.js, server/src/services/goods.service.js
- 상품 price 기본 값 변경
- 0 -> null
- 카테고리 API 적용
- 카테고리 아이콘 css 변경, 라우터 반환 데이터 키 이름 변경
- category -> data
=> [#13, #18] category, goods 수정

client/src/components/Menu.ts, client/src/styles/index.scss, server/src/controllers/goods.controller.js, server/src/queries/goods-chatting.query.js, server/src/queries/goods.query.js, server/src/routes/goods.js
=> [#15, #16, #22] 메뉴 및 채팅 작업 중

client/src/styles/index.scss, server/src/controllers/goods-chatting.controler.js, server/src/queries/goods-chatting.query.js, server/src/services/goods-chatting.service.js, server/src/tmp.html
=> [#22] wip: 채팅방 생성 반환값 변경

server/src/queries/goods-chatting.query.js
resolve #104 
- 이제 더 이상 다른 채팅방이 등장하지 않습니다...
=> bug: :bug: 채팅방 목록 조회 쿼리 수정

README.md, server/.env-example.md, server/config-example.md, server/src/main.js, server/src/routes/goods-photo.js
우테캠 기간동안 배포를 해보지 않아 실습겸 배포 경로를 개인 도메인으로 변경하였습니다!
그리고 버킷 네임에 환경 변수 적용 및 예시 파일을 추가하였습니다.
민상님 면접 화이팅...
:)...
=> 배포 경로 변경 및 env 수정!
